<?php
/**
 * MAMP Database Connection Fix
 * File: mamp_fix.php
 * 
 * Tool khusus untuk mengatasi masalah MySQL di MAMP
 * Jalankan file ini untuk mencoba berbagai kombinasi koneksi MAMP
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$testResults = [];
$message = '';
$messageType = '';

// MAMP default configurations to test
$mampConfigs = [
    [
        'name' => 'MAMP Default (No Password)',
        'host' => 'localhost',
        'port' => '3306',
        'user' => 'root',
        'pass' => ''
    ],
    [
        'name' => 'MAMP Default (Password: root)',
        'host' => 'localhost',
        'port' => '3306',
        'user' => 'root',
        'pass' => 'root'
    ],
    [
        'name' => 'MAMP Port 8889 (No Password)',
        'host' => 'localhost',
        'port' => '8889',
        'user' => 'root',
        'pass' => ''
    ],
    [
        'name' => 'MAMP Port 8889 (Password: root)',
        'host' => 'localhost',
        'port' => '8889',
        'user' => 'root',
        'pass' => 'root'
    ],
    [
        'name' => 'MAMP Socket Connection',
        'host' => 'localhost:/Applications/MAMP/tmp/mysql/mysql.sock',
        'port' => '',
        'user' => 'root',
        'pass' => ''
    ],
    [
        'name' => 'MAMP Socket with Password',
        'host' => 'localhost:/Applications/MAMP/tmp/mysql/mysql.sock',
        'port' => '',
        'user' => 'root',
        'pass' => 'root'
    ]
];

// Test all configurations if requested
if (isset($_GET['test_all'])) {
    foreach ($mampConfigs as $index => $config) {
        $testResults[$index] = testConnection($config);
    }
}

// Test specific configuration
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['test_config'])) {
    $customConfig = [
        'name' => 'Custom Configuration',
        'host' => $_POST['db_host'],
        'port' => $_POST['db_port'],
        'user' => $_POST['db_user'],
        'pass' => $_POST['db_pass']
    ];
    
    $result = testConnection($customConfig);
    if ($result['success']) {
        $message = $result['message'];
        $messageType = 'success';
        
        // Generate new config.php
        $newConfig = generateConfigContent($customConfig);
        file_put_contents('config_new.php', $newConfig);
        $message .= "<br><br>✅ File <strong>config_new.php</strong> telah dibuat! Rename menjadi <strong>config.php</strong> untuk menggunakan konfigurasi ini.";
    } else {
        $message = $result['message'];
        $messageType = 'error';
    }
}

function testConnection($config) {
    try {
        $dsn = "mysql:host={$config['host']}";
        if (!empty($config['port']) && !strpos($config['host'], ':')) {
            $dsn .= ";port={$config['port']}";
        }
        $dsn .= ";charset=utf8mb4";
        
        $pdo = new PDO($dsn, $config['user'], $config['pass'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 5
        ]);
        
        // Get MySQL version
        $stmt = $pdo->query("SELECT VERSION() as version");
        $version = $stmt->fetch(PDO::FETCH_ASSOC)['version'];
        
        // Try to create database
        try {
            $pdo->exec("CREATE DATABASE IF NOT EXISTS aplikasi_madiun CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $dbCreated = true;
        } catch (Exception $e) {
            $dbCreated = false;
        }
        
        return [
            'success' => true,
            'message' => "✅ Connection SUCCESS!<br>MySQL Version: {$version}" . ($dbCreated ? "<br>Database 'aplikasi_madiun' ready!" : ""),
            'config' => $config
        ];
        
    } catch (PDOException $e) {
        return [
            'success' => false,
            'message' => "❌ Connection FAILED: " . $e->getMessage(),
            'config' => $config
        ];
    }
}

function generateConfigContent($config) {
    $host = $config['host'];
    $user = $config['user'];
    $pass = $config['pass'];
    
    return "<?php
/**
 * Aplikasi Pendataan Aplikasi Kabupaten Madiun
 * File: config.php (Generated by MAMP Fix Tool)
 * Konfigurasi database dan security
 */

// Disable error reporting di production
error_reporting(0);
ini_set('display_errors', 0);

// Security headers
header('X-Frame-Options: DENY');
header('X-XSS-Protection: 1; mode=block');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: strict-origin-when-cross-origin');
header('Permissions-Policy: camera=(), microphone=(), geolocation=()');

// Database configuration - MAMP Setup
define('DB_HOST', '{$host}');
define('DB_NAME', 'aplikasi_madiun');
define('DB_USER', '{$user}');
define('DB_PASS', '{$pass}');
define('DB_CHARSET', 'utf8mb4');

// Security configuration
define('CSRF_TOKEN_LENGTH', 32);
define('SESSION_TIMEOUT', 3600); // 1 hour
define('MAX_LOGIN_ATTEMPTS', 5);
define('LOCKOUT_TIME', 900); // 15 minutes
define('RATE_LIMIT_ATTEMPTS', 10);
define('RATE_LIMIT_WINDOW', 300); // 5 minutes

// Site configuration
define('SITE_NAME', 'Pendataan Aplikasi Kabupaten Madiun');
define('ADMIN_EMAIL', 'admin@madiunkab.go.id');

// Data OPD Kabupaten Madiun
\$opdList = [
    \"Badan Kepegawaian Dan Pengembangan Sumber Daya Manusia\",
    \"Badan Kesatuan Bangsa Dan Politik\",
    \"Badan Penanggulangan Bencana Daerah\",
    \"Badan Pendapatan Daerah\",
    \"Badan Pengelolaan Keuangan Dan Aset Daerah\",
    \"Badan Perencanaan Pembangunan, Riset Dan Inovasi Daerah\",
    \"Bagian Administrasi Pembangunan\",
    \"Bagian Hukum\",
    \"Bagian Kesejahteraan Rakyat\",
    \"Bagian Organisasi\",
    \"Bagian Pemerintahan\",
    \"Bagian Pengadaan Barang/Jasa\",
    \"Bagian Perekonomian Dan Sumber Daya Alam\",
    \"Bagian Protokol Dan Komunikasi Pimpinan\",
    \"Bagian Umum\",
    \"Dinas Kependudukan Dan Pencatatan Sipil\",
    \"Dinas Kesehatan\",
    \"Dinas Ketahanan Pangan Dan Peternakan\",
    \"Dinas Komunikasi Dan Informatika\",
    \"Dinas Lingkungan Hidup\",
    \"Dinas Pariwisata, Pemuda Dan Olah Raga\",
    \"Dinas Pekerjaan Umum Dan Penataan Ruang\",
    \"Dinas Pemberdayaan Masyarakat Dan Desa\",
    \"Dinas Penanaman Modal Dan Pelayanan Terpadu Satu Pintu\",
    \"Dinas Pendidikan Dan Kebudayaan\",
    \"Dinas Pengendalian Penduduk Dan Keluarga Berencana, Pemberdayaan Perempuan Dan Perlindungan Anak\",
    \"Dinas Perdagangan, Koperasi Dan Usaha Mikro\",
    \"Dinas Perhubungan\",
    \"Dinas Perpustakaan Dan Kearsipan\",
    \"Dinas Pertanian Dan Perikanan\",
    \"Dinas Perumahan Dan Kawasan Permukiman\",
    \"Dinas Sosial\",
    \"Dinas Tenaga Kerja Dan Perindustrian\",
    \"Inspektorat\",
    \"Kecamatan Balerejo\",
    \"Kecamatan Dagangan\",
    \"Kecamatan Dolopo\",
    \"Kecamatan Geger\",
    \"Kecamatan Gemarang\",
    \"Kecamatan Jiwan\",
    \"Kecamatan Kare\",
    \"Kecamatan Kebonsari\",
    \"Kecamatan Madiun\",
    \"Kecamatan Mejayan\",
    \"Kecamatan Pilangkenceng\",
    \"Kecamatan Saradan\",
    \"Kecamatan Sawahan\",
    \"Kecamatan Wonoasri\",
    \"Kecamatan Wungu\",
    \"Kelurahan Bangunsari (Kecamatan Dolopo)\",
    \"Kelurahan Bangunsari (Kecamatan Mejayan)\",
    \"Kelurahan Krajan (Kecamatan Mejayan)\",
    \"Kelurahan Mlilir (Kecamatan Dolopo)\",
    \"Kelurahan Munggut (Kecamatan Wungu)\",
    \"Kelurahan Nglames (Kecamatan Madiun)\",
    \"Kelurahan Pandean (Kecamatan Mejayan)\",
    \"Kelurahan Wungu (Kecamatan Wungu)\",
    \"Rumah Sakit Umum Daerah Caruban\",
    \"Rumah Sakit Umum Daerah Dolopo\",
    \"Satuan Polisi Pamong Praja Dan Pemadam Kebakaran\",
    \"Sekretariat DPRD\"
];

/**
 * Security Class untuk proteksi aplikasi
 */
class Security {
    private static \$db = null;
    
    public static function initDB() {
        if (self::\$db === null) {
            try {
                \$dsn = \"mysql:host=\" . DB_HOST . \";dbname=\" . DB_NAME . \";charset=\" . DB_CHARSET;
                self::\$db = new PDO(\$dsn, DB_USER, DB_PASS, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES => false,
                    PDO::MYSQL_ATTR_INIT_COMMAND => \"SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci\"
                ]);
            } catch (PDOException \$e) {
                die('Database connection failed');
            }
        }
        return self::\$db;
    }
    
    public static function generateCSRFToken() {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
        \$token = bin2hex(random_bytes(CSRF_TOKEN_LENGTH));
        \$_SESSION['csrf_token'] = \$token;
        \$_SESSION['csrf_time'] = time();
        return \$token;
    }
    
    public static function validateCSRFToken(\$token) {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
        
        if (!isset(\$_SESSION['csrf_token']) || !isset(\$_SESSION['csrf_time'])) {
            return false;
        }
        
        if (time() - \$_SESSION['csrf_time'] > 3600) {
            unset(\$_SESSION['csrf_token'], \$_SESSION['csrf_time']);
            return false;
        }
        
        return hash_equals(\$_SESSION['csrf_token'], \$token);
    }
    
    public static function sanitizeInput(\$input) {
        if (is_array(\$input)) {
            return array_map([self::class, 'sanitizeInput'], \$input);
        }
        return htmlspecialchars(trim(\$input), ENT_QUOTES, 'UTF-8');
    }
    
    public static function validateEmail(\$email) {
        return filter_var(\$email, FILTER_VALIDATE_EMAIL) && strlen(\$email) <= 100;
    }
    
    public static function validatePhone(\$phone) {
        \$phone = preg_replace('/[^0-9+]/', '', \$phone);
        return preg_match('/^(\+62|62|0)[0-9]{8,13}$/', \$phone);
    }
    
    public static function validateURL(\$url) {
        return filter_var(\$url, FILTER_VALIDATE_URL) && strlen(\$url) <= 500;
    }
    
    public static function checkRateLimit(\$action = 'general') {
        return true; // Simplified for MAMP development
    }
    
    public static function getClientIP() {
        return \$_SERVER['REMOTE_ADDR'] ?? '127.0.0.1';
    }
    
    public static function getUserAgent() {
        return \$_SERVER['HTTP_USER_AGENT'] ?? '';
    }
    
    public static function logActivity(\$action, \$tableName = null, \$recordId = null, \$oldValues = null, \$newValues = null) {
        try {
            \$db = self::initDB();
            \$stmt = \$db->prepare(\"
                INSERT INTO activity_logs (action, table_name, record_id, old_values, new_values, ip_address, user_agent, session_id) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            \");
            
            \$sessionId = session_id() ?: null;
            \$stmt->execute([
                \$action,
                \$tableName,
                \$recordId,
                \$oldValues ? json_encode(\$oldValues) : null,
                \$newValues ? json_encode(\$newValues) : null,
                self::getClientIP(),
                self::getUserAgent(),
                \$sessionId
            ]);
        } catch (Exception \$e) {
            // Log error silently
        }
    }
    
    public static function containsXSS(\$input) {
        \$patterns = [
            '/<script[^>]*>.*?<\/script>/is',
            '/javascript:/i',
            '/on\w+\s*=/i',
        ];
        
        foreach (\$patterns as \$pattern) {
            if (preg_match(\$pattern, \$input)) {
                return true;
            }
        }
        
        return false;
    }
    
    public static function regenerateSession() {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
        session_regenerate_id(true);
    }
}
?>";
}

// Get MAMP status
function getMampStatus() {
    $status = [
        'mamp_running' => false,
        'mysql_port' => 'Unknown',
        'php_version' => PHP_VERSION
    ];
    
    // Check if MAMP process is running (macOS specific)
    if (stripos(PHP_OS, 'darwin') !== false) {
        $processes = shell_exec('ps aux | grep -i mamp | grep -v grep');
        $status['mamp_running'] = !empty($processes);
    }
    
    // Try to detect MySQL port from MAMP config
    $mampConfigPath = '/Applications/MAMP/conf/mysql/my.cnf';
    if (file_exists($mampConfigPath)) {
        $config = file_get_contents($mampConfigPath);
        if (preg_match('/port\s*=\s*(\d+)/', $config, $matches)) {
            $status['mysql_port'] = $matches[1];
        }
    }
    
    return $status;
}

$mampStatus = getMampStatus();
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAMP Database Fix - Kabupaten Madiun</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh; padding: 20px;
        }
        .container {
            max-width: 1000px; margin: 0 auto;
            background: white; border-radius: 15px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #ff6b6b 0%, #ee5a52 100%);
            color: white; padding: 30px; text-align: center;
        }
        .header h1 { font-size: 2.2em; margin-bottom: 10px; font-weight: 600; }
        .content { padding: 30px; }
        .mamp-status {
            background: #e8f5e8; border: 1px solid #c3e6c3;
            padding: 20px; border-radius: 10px; margin-bottom: 25px;
        }
        .status-item { margin: 5px 0; }
        .status-ok { color: #27ae60; }
        .status-error { color: #e74c3c; }
        .test-result {
            border: 1px solid #e0e6ed; border-radius: 8px;
            margin-bottom: 10px; padding: 15px;
            background: #f8f9fa;
        }
        .test-result.success { border-left: 5px solid #27ae60; background: #d4edda; }
        .test-result.error { border-left: 5px solid #e74c3c; background: #f8d7da; }
        .btn {
            background: #ff6b6b; color: white; padding: 12px 24px;
            border: none; border-radius: 8px; cursor: pointer;
            text-decoration: none; display: inline-block;
            margin: 5px 5px 5px 0; font-weight: 500;
            transition: all 0.3s ease;
        }
        .btn:hover { background: #ee5a52; transform: translateY(-1px); }
        .btn-success { background: #27ae60; }
        .btn-success:hover { background: #229954; }
        .form-group { margin-bottom: 15px; }
        .form-group label {
            display: block; margin-bottom: 5px;
            font-weight: 600; color: #2c3e50;
        }
        .form-control {
            width: 100%; padding: 10px; border: 1px solid #e0e6ed;
            border-radius: 5px; font-size: 1em;
        }
        .alert { padding: 15px; border-radius: 8px; margin: 15px 0; }
        .alert-success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .alert-error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .config-section {
            background: #f8f9fa; border: 1px solid #e0e6ed;
            padding: 20px; border-radius: 8px; margin: 20px 0;
        }
        .code-block {
            background: #2c3e50; color: #ecf0f1; padding: 15px;
            border-radius: 5px; font-family: 'Courier New', monospace;
            overflow-x: auto; margin: 10px 0;
        }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th, td { padding: 8px 12px; border: 1px solid #ddd; text-align: left; }
        th { background: #2c3e50; color: white; }
        .highlight { background: #fff3cd; padding: 10px; border-radius: 5px; margin: 10px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔧 MAMP Database Fix Tool</h1>
            <p>Khusus untuk mengatasi masalah MySQL di MAMP macOS</p>
        </div>
        
        <div class="content">
            <!-- MAMP Status -->
            <div class="mamp-status">
                <h3>📊 MAMP Environment Status</h3>
                <div class="status-item">
                    <strong>MAMP Status:</strong> 
                    <span class="<?php echo $mampStatus['mamp_running'] ? 'status-ok' : 'status-error'; ?>">
                        <?php echo $mampStatus['mamp_running'] ? '✅ Running' : '❌ Not detected'; ?>
                    </span>
                </div>
                <div class="status-item">
                    <strong>PHP Version:</strong> <span class="status-ok">✅ <?php echo $mampStatus['php_version']; ?></span>
                </div>
                <div class="status-item">
                    <strong>MySQL Port:</strong> <span><?php echo $mampStatus['mysql_port']; ?></span>
                </div>
                <div class="status-item">
                    <strong>Document Root:</strong> <?php echo $_SERVER['DOCUMENT_ROOT']; ?>
                </div>
            </div>
            
            <?php if (!empty($message)): ?>
                <div class="alert alert-<?php echo $messageType; ?>">
                    <?php echo $message; ?>
                </div>
            <?php endif; ?>
            
            <!-- Quick Test Button -->
            <div style="text-align: center; margin: 20px 0;">
                <a href="?test_all=1" class="btn">🧪 Test Semua Konfigurasi MAMP</a>
            </div>
            
            <!-- Test Results -->
            <?php if (!empty($testResults)): ?>
                <div class="config-section">
                    <h3>📋 Hasil Test Konfigurasi MAMP</h3>
                    <?php foreach ($testResults as $result): ?>
                        <div class="test-result <?php echo $result['success'] ? 'success' : 'error'; ?>">
                            <strong><?php echo $result['config']['name']; ?></strong><br>
                            Host: <?php echo $result['config']['host']; ?>
                            <?php if (!empty($result['config']['port'])): ?>
                                | Port: <?php echo $result['config']['port']; ?>
                            <?php endif; ?>
                            | User: <?php echo $result['config']['user']; ?>
                            | Pass: <?php echo empty($result['config']['pass']) ? '(empty)' : '***'; ?>
                            <br>
                            <?php echo $result['message']; ?>
                            
                            <?php if ($result['success']): ?>
                                <br><br>
                                <strong>✅ KONFIGURASI INI BERHASIL!</strong>
                                <div style="margin-top: 10px;">
                                    <form method="post" style="display: inline;">
                                        <input type="hidden" name="test_config" value="1">
                                        <input type="hidden" name="db_host" value="<?php echo $result['config']['host']; ?>">
                                        <input type="hidden" name="db_port" value="<?php echo $result['config']['port']; ?>">
                                        <input type="hidden" name="db_user" value="<?php echo $result['config']['user']; ?>">
                                        <input type="hidden" name="db_pass" value="<?php echo $result['config']['pass']; ?>">
                                        <button type="submit" class="btn btn-success">📝 Generate Config untuk ini</button>
                                    </form>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            
            <!-- Manual Test Form -->
            <div class="config-section">
                <h3>🛠️ Test Manual Configuration</h3>
                <p>Jika konfigurasi otomatis tidak berhasil, coba manual:</p>
                
                <form method="post" action="">
                    <input type="hidden" name="test_config" value="1">
                    
                    <div class="form-group">
                        <label>Database Host:</label>
                        <input type="text" name="db_host" class="form-control" 
                               value="localhost" placeholder="localhost atau localhost:socket_path">
                    </div>
                    
                    <div class="form-group">
                        <label>Database Port:</label>
                        <input type="text" name="db_port" class="form-control" 
                               value="3306" placeholder="3306 atau 8889 (kosongkan jika pakai socket)">
                    </div>
                    
                    <div class="form-group">
                        <label>Database User:</label>
                        <input type="text" name="db_user" class="form-control" value="root">
                    </div>
                    
                    <div class="form-group">
                        <label>Database Password:</label>
                        <input type="password" name="db_pass" class="form-control" 
                               placeholder="Coba: root atau kosongkan">
                    </div>
                    
                    <button type="submit" class="btn">🧪 Test Configuration</button>
                </form>
            </div>
            
            <!-- MAMP Troubleshooting Guide -->
            <div class="config-section">
                <h3>💡 MAMP Troubleshooting Guide</h3>
                
                <div class="highlight">
                    <strong>📌 Langkah-langkah Fix MAMP:</strong>
                </div>
                
                <h4>1. Pastikan MAMP Berjalan</h4>
                <ul style="margin-left: 30px; margin-bottom: 15px;">
                    <li>Buka MAMP application</li>
                    <li>Klik "Start Servers"</li>
                    <li>Pastikan MySQL dan Apache berjalan (lampu hijau)</li>
                </ul>
                
                <h4>2. Cek MySQL Password di MAMP</h4>
                <ul style="margin-left: 30px; margin-bottom: 15px;">
                    <li>Buka MAMP → Preferences → Ports</li>
                    <li>Catat MySQL port (biasanya 3306 atau 8889)</li>
                    <li>Buka phpMyAdmin via MAMP start page</li>
                    <li>Jika bisa masuk tanpa password → password kosong</li>
                    <li>Jika diminta password → coba 'root'</li>
                </ul>
                
                <h4>3. Alternative: Reset MySQL Password</h4>
                <div class="code-block">
                    # Buka Terminal dan jalankan:<br>
                    /Applications/MAMP/Library/bin/mysql -u root -p<br>
                    # Jika diminta password, coba 'root' atau enter<br><br>
                    
                    # Dalam MySQL console:<br>
                    ALTER USER 'root'@'localhost' IDENTIFIED BY '';<br>
                    FLUSH PRIVILEGES;<br>
                    EXIT;
                </div>
                
                <h4>4. Cek MAMP MySQL Socket</h4>
                <p>Jika port connection gagal, coba socket connection:</p>
                <div class="code-block">
                    Host: localhost:/Applications/MAMP/tmp/mysql/mysql.sock<br>
                    Port: (kosongkan)<br>
                    User: root<br>
                    Pass: (kosong atau 'root')
                </div>
            </div>
            
            <!-- Quick Actions -->
            <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e0e6ed;">
                <a href="db_check.php" class="btn">🩺 Back to Diagnostic</a>
                <a href="setup.php" class="btn">🚀 Setup Wizard</a>
                <a href="index.php" class="btn btn-success">🏠 Main App</a>
            </div>
            
            <?php if (file_exists('config_new.php')): ?>
                <div class="alert alert-success" style="margin-top: 20px;">
                    <strong>📄 File config_new.php sudah ada!</strong><br>
                    Rename file ini menjadi <strong>config.php</strong> untuk menggunakan konfigurasi yang benar.
                    <br><br>
                    <div class="code-block">
                        # Di Terminal:<br>
                        cd <?php echo dirname(__FILE__); ?><br>
                        mv config_new.php config.php
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>