<?php
/**
 * Aplikasi Pendataan Aplikasi Kabupaten Madiun
 * File: config.php (Generated by MAMP Fix Tool)
 * Konfigurasi database dan security
 */

// Disable error reporting di production
error_reporting(0);
ini_set('display_errors', 0);

// Security headers
header('X-Frame-Options: DENY');
header('X-XSS-Protection: 1; mode=block');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: strict-origin-when-cross-origin');
header('Permissions-Policy: camera=(), microphone=(), geolocation=()');

// Database configuration - MAMP Setup
define('DB_HOST', 'localhost');
define('DB_NAME', 'aplikasi_madiun');
define('DB_USER', 'root');
define('DB_PASS', 'root');
define('DB_CHARSET', 'utf8mb4');

// Security configuration
define('CSRF_TOKEN_LENGTH', 32);
define('SESSION_TIMEOUT', 3600); // 1 hour
define('MAX_LOGIN_ATTEMPTS', 5);
define('LOCKOUT_TIME', 900); // 15 minutes
define('RATE_LIMIT_ATTEMPTS', 10);
define('RATE_LIMIT_WINDOW', 300); // 5 minutes

// Site configuration
define('SITE_NAME', 'Pendataan Aplikasi Kabupaten Madiun');
define('ADMIN_EMAIL', 'admin@madiunkab.go.id');

// Data OPD Kabupaten Madiun
$opdList = [
    "Badan Kepegawaian Dan Pengembangan Sumber Daya Manusia",
    "Badan Kesatuan Bangsa Dan Politik",
    "Badan Penanggulangan Bencana Daerah",
    "Badan Pendapatan Daerah",
    "Badan Pengelolaan Keuangan Dan Aset Daerah",
    "Badan Perencanaan Pembangunan, Riset Dan Inovasi Daerah",
    "Bagian Administrasi Pembangunan",
    "Bagian Hukum",
    "Bagian Kesejahteraan Rakyat",
    "Bagian Organisasi",
    "Bagian Pemerintahan",
    "Bagian Pengadaan Barang/Jasa",
    "Bagian Perekonomian Dan Sumber Daya Alam",
    "Bagian Protokol Dan Komunikasi Pimpinan",
    "Bagian Umum",
    "Dinas Kependudukan Dan Pencatatan Sipil",
    "Dinas Kesehatan",
    "Dinas Ketahanan Pangan Dan Peternakan",
    "Dinas Komunikasi Dan Informatika",
    "Dinas Lingkungan Hidup",
    "Dinas Pariwisata, Pemuda Dan Olah Raga",
    "Dinas Pekerjaan Umum Dan Penataan Ruang",
    "Dinas Pemberdayaan Masyarakat Dan Desa",
    "Dinas Penanaman Modal Dan Pelayanan Terpadu Satu Pintu",
    "Dinas Pendidikan Dan Kebudayaan",
    "Dinas Pengendalian Penduduk Dan Keluarga Berencana, Pemberdayaan Perempuan Dan Perlindungan Anak",
    "Dinas Perdagangan, Koperasi Dan Usaha Mikro",
    "Dinas Perhubungan",
    "Dinas Perpustakaan Dan Kearsipan",
    "Dinas Pertanian Dan Perikanan",
    "Dinas Perumahan Dan Kawasan Permukiman",
    "Dinas Sosial",
    "Dinas Tenaga Kerja Dan Perindustrian",
    "Inspektorat",
    "Kecamatan Balerejo",
    "Kecamatan Dagangan",
    "Kecamatan Dolopo",
    "Kecamatan Geger",
    "Kecamatan Gemarang",
    "Kecamatan Jiwan",
    "Kecamatan Kare",
    "Kecamatan Kebonsari",
    "Kecamatan Madiun",
    "Kecamatan Mejayan",
    "Kecamatan Pilangkenceng",
    "Kecamatan Saradan",
    "Kecamatan Sawahan",
    "Kecamatan Wonoasri",
    "Kecamatan Wungu",
    "Kelurahan Bangunsari (Kecamatan Dolopo)",
    "Kelurahan Bangunsari (Kecamatan Mejayan)",
    "Kelurahan Krajan (Kecamatan Mejayan)",
    "Kelurahan Mlilir (Kecamatan Dolopo)",
    "Kelurahan Munggut (Kecamatan Wungu)",
    "Kelurahan Nglames (Kecamatan Madiun)",
    "Kelurahan Pandean (Kecamatan Mejayan)",
    "Kelurahan Wungu (Kecamatan Wungu)",
    "Rumah Sakit Umum Daerah Caruban",
    "Rumah Sakit Umum Daerah Dolopo",
    "Satuan Polisi Pamong Praja Dan Pemadam Kebakaran",
    "Sekretariat DPRD"
];

/**
 * Security Class untuk proteksi aplikasi
 */
class Security {
    private static $db = null;
    
    public static function initDB() {
        if (self::$db === null) {
            try {
                $dsn = "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=" . DB_CHARSET;
                self::$db = new PDO($dsn, DB_USER, DB_PASS, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES => false,
                    PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
                ]);
            } catch (PDOException $e) {
                die('Database connection failed');
            }
        }
        return self::$db;
    }
    
    public static function generateCSRFToken() {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
        $token = bin2hex(random_bytes(CSRF_TOKEN_LENGTH));
        $_SESSION['csrf_token'] = $token;
        $_SESSION['csrf_time'] = time();
        return $token;
    }
    
    public static function validateCSRFToken($token) {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
        
        if (!isset($_SESSION['csrf_token']) || !isset($_SESSION['csrf_time'])) {
            return false;
        }
        
        if (time() - $_SESSION['csrf_time'] > 3600) {
            unset($_SESSION['csrf_token'], $_SESSION['csrf_time']);
            return false;
        }
        
        return hash_equals($_SESSION['csrf_token'], $token);
    }
    
    public static function sanitizeInput($input) {
        if (is_array($input)) {
            return array_map([self::class, 'sanitizeInput'], $input);
        }
        return htmlspecialchars(trim($input), ENT_QUOTES, 'UTF-8');
    }
    
    public static function validateEmail($email) {
        return filter_var($email, FILTER_VALIDATE_EMAIL) && strlen($email) <= 100;
    }
    
    public static function validatePhone($phone) {
        $phone = preg_replace('/[^0-9+]/', '', $phone);
        return preg_match('/^(\+62|62|0)[0-9]{8,13}$/', $phone);
    }
    
    public static function validateURL($url) {
        return filter_var($url, FILTER_VALIDATE_URL) && strlen($url) <= 500;
    }
    
    public static function checkRateLimit($action = 'general') {
        return true; // Simplified for MAMP development
    }
    
    public static function getClientIP() {
        return $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1';
    }
    
    public static function getUserAgent() {
        return $_SERVER['HTTP_USER_AGENT'] ?? '';
    }
    
    public static function logActivity($action, $tableName = null, $recordId = null, $oldValues = null, $newValues = null) {
        try {
            $db = self::initDB();
            $stmt = $db->prepare("
                INSERT INTO activity_logs (action, table_name, record_id, old_values, new_values, ip_address, user_agent, session_id) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ");
            
            $sessionId = session_id() ?: null;
            $stmt->execute([
                $action,
                $tableName,
                $recordId,
                $oldValues ? json_encode($oldValues) : null,
                $newValues ? json_encode($newValues) : null,
                self::getClientIP(),
                self::getUserAgent(),
                $sessionId
            ]);
        } catch (Exception $e) {
            // Log error silently
        }
    }
    
    public static function containsXSS($input) {
        $patterns = [
            '/<script[^>]*>.*?<\/script>/is',
            '/javascript:/i',
            '/on\w+\s*=/i',
        ];
        
        foreach ($patterns as $pattern) {
            if (preg_match($pattern, $input)) {
                return true;
            }
        }
        
        return false;
    }
    
    public static function regenerateSession() {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
        session_regenerate_id(true);
    }
}
?>